PD-37 Add HelpCommand and HelpModal
Jerrylum/protocol-diagram pull request #30
Opened 2023-10-04 09:52 UTC by crapper

2023-10-04 10:00 UTC, Jerrylum requested changes

2023-10-05 06:32 UTC, crapper commented on src/command/Commands.ts
> +  let first = cmd.usage;
Updated. Thank you for the reminder.

2023-10-05 06:33 UTC, crapper commented on src/command/Commands.ts
> +  if (cmd.name) {
Removed, there should not be any class without a name, thank you.

2023-10-05 06:35 UTC, crapper commented on src/command/Commands.ts
> +export function getCommandUsage(cmd: Command): string {
Added, thank you for the reminder!

2023-10-05 06:58 UTC, Jerrylum approved these changes
LGTM

2023-10-05 06:58 UTC, merged